
---------- Create initial list entries ----------
BEGIN;

CREATE SCHEMA IF NOT EXISTS favorite_songs_of_year;

CREATE TABLE IF NOT EXISTS favorite_songs_of_year.lists (
    year         INT PRIMARY KEY CHECK (year BETWEEN 1900 AND 2100),
    comment      TEXT NOT NULL,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
    date_updated TIMESTAMPTZ
);

---------- Update the date_updated column when the comment is updated ----------
CREATE OR REPLACE FUNCTION favorite_songs_of_year.set_comments_date_updated()
    RETURNS TRIGGER
    LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.date_updated := now();
    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS set_comments_date_updated
    ON favorite_songs_of_year.lists;

CREATE TRIGGER set_comments_date_updated
    BEFORE UPDATE OF comment ON favorite_songs_of_year.lists
    FOR EACH ROW
    WHEN (OLD.comment IS DISTINCT FROM NEW.comment)
EXECUTE FUNCTION favorite_songs_of_year.set_comments_date_updated();

---------- Initial comments ----------
INSERT INTO favorite_songs_of_year.lists (year, comment)
VALUES
    (2017, '2017 was the first year I made this list, and was before I made the rule of only one song per artist.  Looking back on it, I most definitely would switch out about half the songs with other ones released that year.  I find this to be the case with every year, however.  Sometimes it''s because my taste in music evolves, but it mostly seems to be because I start listening to a song the year after it''s released, especially if it was late in the year.  This is the year where it''s the former rather than the latter, however.' || E'\n\n' || 'Out of my existing list, though, the three that I''ve kept listening to consistently since are Bear Claws, How Do You Feel?, and Less Than.'),
    (2018, 'After not liking that my 2017 list contained a couple songs from the same artist, I decided to impose the rule of no more than one song per artist.  An artist/band being featured on another artist/band''s song is okay, but it explicitly cannot be their song.  This made it more interesting for me since not only did I have to narrow down to a single song off of an album, I had to listen to songs and albums by other artists I may not have listened to before.' || E'\n\n' || 'As far as songs I would switch out with other ones released in 2018, I would probably switch out only a couple at most.  I really enjoyed most of the music I listened to that year and haven''t discovered more than a couple songs released in 2018 since that I would replace the others with.' || E'\n\n' || 'Out of my existing list, the three I''ve continued listening to the most is difficult to pin down, but most likely Starlight, What is Love?, and Voices in My Head.'),
    (2019, 'This year actually was somewhat difficult to get enough songs for the list.  There were five albums that I primarily listened to because they were so good, meaning I didn''t listen to more artists I would have liked to because I had those albums almost exclusively on repeat at various times throughout the year.  If I did not create the rule of no more than one song per artist this list would have consisted of songs primarily by FEVER 333, BABYMETAL, TWICE, and The Maine.  I''m pretty sure the entire summer of 2019 I listened to almost exclusively FEVER 333, and October and November seemed as if BABYMETAL and TWICE had a reservation for my time.  I ultimately decided on enough songs to consist of a solid list, though.' || E'\n\n' || 'As with 2018, there''s one song, maybe two I would switch out with a song on this list, but overall I think the list was a pretty good one.' || E'\n\n' || 'Out of my existing list, the three I''ve continued listening to the most, without question, are Brand New Day, LOVE FOOLISH, and THE INNOCENT.'),
    (2020, 'TWICE makes their third appearance, as does BABYMETAL (even if it is just a feature)!  If I had been more into TWICE in 2017, they would have made an appearance every year since I''ve started this.  Overall, I was somewhat pleased with the music released in 2020.  System of a Down, a favorite of mine, released their first music in over a decade.  Selena Gomez and DREAMCATCHER, a new find for me, had superb albums released at the beginning of the year (I vividly remember this because of COVID), so it was difficult picking one song from each album.  Besides those and the FEVER 333 song, though, I kind of struggled to really get a solid top 13.  John the Ghost is the singer for one of my favorite bands that has made many appearances already (The Maine), so that wasn''t very difficult, but otherwise there are a few songs I haven''t listened to much since.  I had hoped that quarantine would provide artists with some more time, but of course they may have easily just taken it as time off.  I had several concerts lined up for this year, and every single one got cancelled, so it would make sense.' || E'\n\n' || 'Out of this year, the three songs I''ve continued to listen to are A Sweeter Place, UP NO MORE, and PRESENCE IS STRENGTH.'),
    (2021, 'This year was, like 2019, a bit difficult to compile.  Most of the songs are songs I listened to towards the beginning of the year.  TWICE again makes an appearance, and another K-Pop artist (IU) makes a first appearance.  I''ve listened to several of the artists on the list previously, so it was nice to hear their newer music and to say I''m still a fan.  The Hunna was a band I discovered at a show for Jimmy Eat World years ago, so I was happy to enjoy some of their newer music.  As for some of the others (The Blue Stones, ERRA, IU, and Teenage Wrist), I loved discovering their music this year and obsessively listening to it.  While I was down in Georgia for work, these artists accompanied me while I was sitting in a warehouse for 11 hours a day.' || E'\n\n' || 'For this year, the three songs that I''ve religiously listened to are Bad Place, Lilac, and Always The Same.  Lilac is a song I listened to over 40 times in a single day while I was in Georgia, for example!  I can''t say I''m proud of that detail.'),
    (2022, 'This was once again another year that I found it difficult to find enough new music to fill the list.  ERRA and The Blue Stones make a return, and Electric Callboy was a fantastic discovery!  I was not surprised that TWICE made the list again.  When I first listened to Talk that Talk I wasn''t that impressed, but it quickly became one of my favorites of theirs.' || E'\n\n' || 'Despite the trouble I had with finding songs to add to the list, I listen to most of the songs on this list a lot to this day.  Now that I''ve given more music from the year a chance there are songs I would certainly swap out with others that are on the list, but overall I enjoyed it.  The three songs on this list that I listen to the most still today are Neon, Loved You a Little, and Talk that Talk.'),
    (2023, 'Finally, for the first time since I started this list, Avenged Sevenfold released a new album (their first since 2016).  Avenged Sevenfold has been my all time favorite band since 2008, so I always celebrate new music from them.  In 2017 they began "evolving" their album from 2016 by adding covers, but I didn''t quite want to add them to the list.  Besides that, there are several new additions that I am happy to have learned about (notably Calva Louise and Make Them Suffer).  MISAMO was a bit of a sheepish addition, however, since they''re a subunit of TWICE.' || E'\n\n' || 'I still find myself listening to nearly every song on this list, and besides maybe one or two I can''t think of many other songs I would replace something on this list with.  Out of the songs on it, though, I''d say that the three songs I continue to listen to the most to this day are Cosmic, Ghost Of Me, and Essence.'),
    (2024, 'Unlike a couple of the previous years, I found it difficult to actually trim this down to just 13. Unsurprisingly, TWICE has made it once again, and I''m sure this will be the case for 2025. I''m writing this retrospective a bit earlier than I have in previous years, so I only have maybe one or two songs that I''d replace in this list now.  Overall, however, I do like how diverse the music in this list seems to be, genre-wise; it''s a pretty solid representation of the music I listen to.  Little Big is a group my sister, friend, and I have been listening to since late 2019.  They''re a weird Russian rave group that makes some funny music and great music videos, and my sister, my friend, and I have gone to Chicago and Detroit to see them live now, and it was great both times.' || E'\n\n' || 'Out of the songs in 2024, the three I certainly listen to the most still are RATATA, Suffocate, and Good Graces.'),
    (2025, 'This year was surprisingly pretty difficult to narrow down to only 13 songs. Avenged Sevenfold is my favorite band, as I''ve mentioned, but they released a song that wasn''t even close to making the cut. TWICE even just barely made it as well. Although I''m not a Sleep Token fan, Caramel is an incredible song, and it ended up being my most played song of the year, so it''s no surprise that made the list. Three Days Grace was a surprising entry, too! The very first song I ever learned on guitar was Animal I Have Become over 15 years ago, and I stopped listening once Adam Gontier left, so it was refreshing being able to include them finally. Despite having not watched K-Pop Demon Hunters, Golden was a must include, considering I AM by IVE was included a couple years ago and Golden sounds almost identical to that song. 2025 was actually a pretty great year for music.')
ON CONFLICT (year) DO NOTHING;

CREATE TABLE IF NOT EXISTS favorite_songs_of_year.songs (
    id               INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    song_name        TEXT NOT NULL,
    artist           TEXT NOT NULL,
    album            TEXT NOT NULL,
    genre            TEXT NOT NULL,
    song_length      TIME NOT NULL,
    apple_music_link TEXT NOT NULL,
    spotify_link     TEXT NOT NULL,
    youtube_link     TEXT NOT NULL,
    year             INT  NOT NULL,
    is_single        BOOL NOT NULL,
    CONSTRAINT uq_favorite_songs_song_artist UNIQUE (song_name, artist),
    CONSTRAINT fk_favorite_songs_year
    FOREIGN KEY (year)
        REFERENCES favorite_songs_of_year.lists (year)
        ON DELETE CASCADE
);

---------- Initial songs ----------
INSERT INTO favorite_songs_of_year.songs (
    song_name,
    artist,
    album,
    genre,
    song_length,
    apple_music_link,
    spotify_link,
    youtube_link,
    year,
    is_single
)
VALUES ('Bear Claws', 'The Academic', 'Tales from the Backseat', 'Alternative', '00:03:33',
        'https://music.apple.com/us/album/bear-claws/1710236954?i=1710237207',
        'https://open.spotify.com/album/4YP202ZTbhy7F9fSQsbKPL?highlight=spotify:track:7oBPSh4C7vvQ9F1mnyqwVe',
        'https://www.youtube.com/watch?v=hXoBj5HZ1hU', 2017, TRUE),
       ('Never Sorry', 'All That Remains', 'Madness', 'Heavy Metal', '00:03:38',
        'https://music.apple.com/us/album/never-sorry/1440946633?i=1440946653',
        'https://open.spotify.com/album/1tb0QLGgdyuewhLFN4iKnj?highlight=spotify:track:3LNYKMfgG2UScseEv92XeP',
        'https://www.youtube.com/watch?v=mBNGoE_22JU', 2017, FALSE),
       ('Shape of You', 'Ed Sheeran', '÷', 'Pop', '00:03:54',
        'https://music.apple.com/us/album/shape-of-you/1193701079?i=1193701392',
        'https://open.spotify.com/album/3T4tUhGYeRNVUGevb0wThu?highlight=spotify:track:7qiZfU4dY1lWllzX7mPBI3',
        'https://www.youtube.com/watch?v=JGwWNGJdvx8', 2017, FALSE),
       ('Sleeping Powder', 'Gorillaz', 'Sleeping Powder - Single', 'Alternative', '00:02:46',
        'https://music.apple.com/us/album/sleeping-powder/1247590076?i=1247590729',
        'https://open.spotify.com/album/5D31GSU5erwgjB6uvLzlcu?highlight=spotify:track:5pE9vMyvVNOpZFutt6lyy4',
        'https://www.youtube.com/watch?v=GzJGWAfmBco', 2017, TRUE),
       ('Call Ins', 'He Is Legend', 'Few', 'Rock', '00:03:42',
        'https://music.apple.com/us/album/call-ins/1661148127?i=1661149216',
        'https://open.spotify.com/album/1uXJ01pmkQzFFvb7h6sO0y?highlight=spotify:track:2sIPY6ELRwL5ZKswDhAdpD',
        'https://www.youtube.com/watch?v=Lwx8k5Gv53I', 2017, FALSE),
       ('State of the Art', 'Incubus', '8', 'Alternative', '00:03:47',
        'https://music.apple.com/us/album/state-of-the-art/1440881253?i=1440881901',
        'https://open.spotify.com/album/3YdvnTLTd343C1osvUChnA?highlight=spotify:track:7mVIEjxqffN2F1Q3NUHKPG',
        'https://www.youtube.com/watch?v=dZSTI-xkXko', 2017, FALSE),
       ('Black Butterflies and Deja Vu', 'The Maine', 'Lovely Little Lonely', 'Alternative', '00:03:23',
        'https://music.apple.com/us/album/black-butterflies-and-d%C3%A9j%C3%A0-vu/1209457468?i=1209457776',
        'https://open.spotify.com/album/2jStuYeaRty1cwxjoxfo9K?highlight=spotify:track:6QZ8h3RqIgTRTo3hfaqryx',
        'https://www.youtube.com/watch?v=wHm2bQRJIaw', 2017, FALSE),
       ('How Do You Feel?', 'The Maine', 'Lovely Little Lonely', 'Alternative', '00:04:22',
        'https://music.apple.com/us/album/how-do-you-feel/1209457468?i=1209458135',
        'https://open.spotify.com/album/2jStuYeaRty1cwxjoxfo9K?highlight=spotify:track:6AH3IbS61PiabZYKVBqKAk',
        'https://www.youtube.com/watch?v=tku0H7YeMeA', 2017, FALSE),
       ('Less Than', 'Nine Inch Nails', 'Add Violence - EP', 'Alternative', '00:03:30',
        'https://music.apple.com/us/album/less-than/1847481807?i=1847481808',
        'https://open.spotify.com/album/28DJ00Yr5oOhH0uOUgTQwc?highlight=spotify:track:7jDKJSjIjT93v7brsZDcoT',
        'https://www.youtube.com/watch?v=gDV-dOvqKzQ', 2017, FALSE),
       ('The Doomed', 'A Perfect Circle', 'Eat the Elephant', 'Rock', '00:04:42',
        'https://music.apple.com/us/album/the-doomed/1471554984?i=1471555176',
        'https://open.spotify.com/album/3Jr1RhAyndBxtyi8rJs3Op?highlight=spotify:track:44OUZyiPnJc4pOZw4J6pid',
        'https://www.youtube.com/watch?v=SDvfbvuJtS8', 2017, TRUE),
       ('Fabuless', 'Stone Sour', 'Hydrograd', 'Hard Rock', '00:04:01',
        'https://music.apple.com/us/album/fabuless/1229163139?i=1229163686',
        'https://open.spotify.com/album/4PERSgw7TXqpEZlIVN6zHr?highlight=spotify:track:72GH838JaxrCA8IFcXqgXm',
        'https://www.youtube.com/watch?v=Jwglgn1mo3M', 2017, FALSE),
       ('Rx (Medicate)', 'Theory of a Deadman', 'Wake Up Call', 'Rock', '00:03:53',
        'https://music.apple.com/us/album/rx-medicate/1262126917?i=1262126920',
        'https://open.spotify.com/album/1P2L7DD1DCqb0VfpMyByLl?highlight=spotify:track:2UZtI2HUyLRzqBjodvcUmY',
        'https://www.youtube.com/watch?v=iwxfmYR7ItM', 2017, FALSE),
       ('Feels Like Summer', 'Weezer', 'Pacific Daydream', 'Alternative', '00:03:15',
        'https://music.apple.com/us/album/feels-like-summer/1270328038?i=1270328050',
        'https://open.spotify.com/album/3EwfQtjvyRAXsPWAKO5FDP?highlight=spotify:track:2jz1bw1p0WQj0PDnVDP0uY',
        'https://www.youtube.com/watch?v=efPWrIvzGgc', 2017, FALSE),

       ('Voices in my Head', 'Ashley Tisdale', 'Symptoms', 'Pop', '00:03:19',
        'https://music.apple.com/us/album/voices-in-my-head/1457934050?i=1457934215',
        'https://open.spotify.com/album/2SeQhMEDBwMPuU1yykP2mh?highlight=spotify:track:0Tyt3SyqRIsN0XHRyhD75J',
        'https://www.youtube.com/watch?v=y-Wv9sAbPOI', 2018, TRUE),
       ('Starlight', 'BABYMETAL', 'METAL GALAXY', 'Metal', '00:03:36',
        'https://music.apple.com/us/album/starlight/1830275477?i=1830275870',
        'https://open.spotify.com/album/6rxRhft7JZtXavzHP2g2el?highlight=spotify:track:2iAIBHvSNH5oHrCCpmeaBV',
        'https://www.youtube.com/watch?v=hPVx7IazcEw', 2018, TRUE),
       ('Zombie', 'Bad Wolves', 'Disobey', 'Hard Rock', '00:04:15',
        'https://music.apple.com/us/album/zombie/1695704585?i=1695704591',
        'https://open.spotify.com/album/5hDwXxawZfYuNxylzGXcqt?highlight=spotify:track:1eadPrzB2P0ikQcqhKSAtv',
        'https://www.youtube.com/watch?v=9XaS93WMRQQ', 2018, FALSE),
       ('Dice', 'BAND-MAID', 'World Domination', 'Rock', '00:04:03',
        'https://music.apple.com/us/album/dice/1339560562?i=1339560706',
        'https://open.spotify.com/album/7126IZsEVmCi2VxASFaI1c?highlight=spotify:track:26P0PvxuRYcgzxeHZ4rjD0',
        'https://www.youtube.com/watch?v=ZpAYnVJX9CY', 2018, FALSE),
       ('The Dark Sentencer', 'Coheed and Cambria', 'The Unheavenly Creatures', 'Rock', '00:07:45',
        'https://music.apple.com/us/album/the-dark-sentencer/1403404699?i=1403404719',
        'https://open.spotify.com/album/42S0lDJT9wHKCVaMGgqKdm?highlight=spotify:track:0mP3O68nZjScrbgiD9UilH',
        'https://www.youtube.com/watch?v=T3zm1_JSPOQ', 2018, FALSE),
       ('Age of Man', 'Greta Van Fleet', 'Anthem of the Peaceful Army', 'Rock', '00:06:06',
        'https://music.apple.com/us/album/age-of-man/1435351050?i=1435351490',
        'https://open.spotify.com/album/7zeCZY6rQRufc8IHGKyXGX?highlight=spotify:track:54DIzLw4LLxB3n1XiiQftU',
        'https://www.youtube.com/watch?v=Wd9te6ZQXpQ', 2018, FALSE),
       ('Supplies', 'Justin Timberlake', 'Man of the Woods', 'Pop', '00:03:46',
        'https://music.apple.com/us/album/supplies/1330759954?i=1330760178',
        'https://open.spotify.com/album/01l3jTY261V3CESZR4dABz?highlight=spotify:track:6jT85s2dZ55HBqjXYi2rfI',
        'https://www.youtube.com/watch?v=M4vnmgZLA8s', 2018, FALSE),
       ('Over and Out', 'Nine Inch Nails', 'Bad Witch', 'Alternative', '00:07:50',
        'https://music.apple.com/us/album/over-and-out/1847482590?i=1847482600',
        'https://open.spotify.com/album/0Q2o6ioxIOlKPvRdG1K5da?highlight=spotify:track:1J8CqSsS6ErrveimQyCvZa',
        'https://www.youtube.com/watch?v=gsj5DDWcB24', 2018, FALSE),
       ('Disillusioned', 'A Perfect Circle', 'Eat the Elephant', 'Rock', '00:05:54',
        'https://music.apple.com/us/album/disillusioned/1471554984?i=1471555174',
        'https://open.spotify.com/album/3Jr1RhAyndBxtyi8rJs3Op?highlight=spotify:track:1O9DWF3578RHMxZg2nLPeM',
        'https://www.youtube.com/watch?v=BIsH686xWl0', 2018, FALSE),
       ('Body Talks', 'The Struts', 'YOUNG & DANGEROUS', 'Rock', '00:02:58',
        'https://music.apple.com/us/album/body-talks/1435805372?i=1435805536',
        'https://open.spotify.com/album/1mFRTnYk72zZfVk7l25G3g?highlight=spotify:track:6spaGIZEfeDYlgAupMI34k',
        'https://www.youtube.com/watch?v=Hc3XIbUuTMc', 2018, FALSE),
       ('COLORS', 'Tenacious D', 'Post-Apocalypto', 'Rock', '00:02:20',
        'https://music.apple.com/us/album/colors/1434624186?i=1434624879',
        'https://open.spotify.com/album/4O83oaztVuBlPDrp50Q3mh?highlight=spotify:track:40rChMoUd1VXb4TKgTuTSP',
        'https://www.youtube.com/watch?v=11Hy_8gZPnQ', 2018, FALSE),
       ('My Blood', 'twenty one pilots', 'Trench', 'Alternative', '00:03:49',
        'https://music.apple.com/us/album/my-blood/1422828208?i=1422828213',
        'https://open.spotify.com/album/621cXqrTSSJi1WqDMSLmbL?highlight=spotify:track:5HeKOKc4phmLn8e4I7EkzD',
        'https://www.youtube.com/watch?v=8mn-FFjIbo8', 2018, FALSE),
       ('What is Love?', 'TWICE', 'What is Love? - EP', 'K-Pop', '00:03:28',
        'https://music.apple.com/us/album/what-is-love/1555390082?i=1555390083',
        'https://open.spotify.com/album/31UY383FD6tNuPSUJ8LrTG?highlight=spotify:track:7ogyhvfoPn27BDswIUHMm1',
        'https://www.youtube.com/watch?v=i0p1bmr0EmE', 2018, FALSE),

       ('Feeling so Good', 'Ashley Tisdale', 'Symptoms', 'Pop', '00:03:07',
        'https://music.apple.com/us/album/feeling-so-good/1457934050?i=1457934217',
        'https://open.spotify.com/album/2SeQhMEDBwMPuU1yykP2mh?highlight=spotify:track:4GAFlFLouTialsJv1kiKaC',
        'https://www.youtube.com/watch?v=Y-m9cl1Hxeg', 2019, FALSE),
       ('Brand New Day', 'BABYMETAL', 'METAL GALAXY', 'Metal', '00:04:11',
        'https://music.apple.com/us/album/brand-new-day-feat-scott-lepage-tim-henson/1830275477?i=1830275852',
        'https://open.spotify.com/album/6rxRhft7JZtXavzHP2g2el?highlight=spotify:track:0FpJdOwxVYjN0UCIG6ovcR',
        'https://www.youtube.com/watch?v=k0b1NNp0gBc', 2019, FALSE),
       ('Promise Me', 'Badflower', 'OK, I''M SICK', 'Alternative', '00:03:50',
        'https://music.apple.com/us/album/promise-me/1440357164?i=1440357294',
        'https://open.spotify.com/album/08VFvUyNPi6G0tc1d4DPU4?highlight=spotify:track:5TU1cWjUGyVKjSnIIxRSEf',
        'https://www.youtube.com/watch?v=yhNp7i4xaUU', 2019, FALSE),
       ('mother tongue', 'Bring Me the Horizon', 'amo', 'Rock', '00:03:37',
        'https://music.apple.com/us/album/mother-tongue/1439239477?i=1439240076',
        'https://open.spotify.com/album/04mkS7FooK8fRbB626T9NR?highlight=spotify:track:5IwUFTiNkarb5HEtNRtRtc',
        'https://www.youtube.com/watch?v=RZekS_waLUY', 2019, FALSE),
       ('THE INNOCENT', 'FEVER 333', 'STRENGTH IN NUMB333RS', 'Hard Rock', '00:03:22',
        'https://music.apple.com/us/album/the-innocent/1441326645?i=1441326655',
        'https://open.spotify.com/album/5PvosHtqCuqLK8A131lGZf?highlight=spotify:track:1Y2FJpsOmfqfFuqS0KatUu',
        'https://www.youtube.com/watch?v=uDUPK_Lz9eo', 2019, FALSE),
       ('Flowers on the Grave', 'The Maine', 'You Are OK', 'Alternative', '00:09:23',
        'https://music.apple.com/us/album/flowers-on-the-grave/1451377141?i=1451377387',
        'https://open.spotify.com/album/1fPQaZhs8bWeL3Io9u4TsD?highlight=spotify:track:2rsgWz1uCAsUlcjD12axTx',
        'https://www.youtube.com/watch?v=4VuzrfG3uOA', 2019, FALSE),
       ('Miracle Man', 'Oliver Tree', 'Ugly is Beautiful', 'Alternative', '00:02:05',
        'https://music.apple.com/us/album/miracle-man/1514394064?i=1514394491',
        'https://open.spotify.com/album/1HmWQo43Gt8BR2dylfv3o4?highlight=spotify:track:2PFnwW05Wh0MYkfZxSwfuf',
        'https://www.youtube.com/watch?v=EBLF26-Irdc', 2019, FALSE),
       ('Diseased Almost', 'Puddle of Mudd', 'Welcome to Galvania', 'Rock', '00:03:42',
        'https://music.apple.com/us/album/diseased-almost/1471037643?i=1471037656',
        'https://open.spotify.com/album/2Fn2AgdIOCUDfi4lHmX0qG?highlight=spotify:track:7HaT692mQsfESjwD3TH8Uo',
        'https://www.youtube.com/watch?v=ZXEnxNUqWB4', 2019, FALSE),
       ('Beast', 'Saint Asonia', 'Flawed Design', 'Rock', '00:03:27',
        'https://music.apple.com/us/album/beast/1660374414?i=1660374631',
        'https://open.spotify.com/album/59pOP9owt8GjGJ2aTVmcHG?highlight=spotify:track:0AVKG4Qu7ubCzPlrWuhpMS',
        'https://www.youtube.com/watch?v=nlMVbqcX06w', 2019, FALSE),
       ('Nero Forte', 'Slipknot', 'We Are Not Your Kind', 'Metal', '00:05:15',
        'https://music.apple.com/us/album/nero-forte/1463706038?i=1463706044',
        'https://open.spotify.com/album/754RY5WpZ2LTUZsk8kDBju?highlight=spotify:track:56fiFTRrSiHHH3gBeaTg2P',
        'https://www.youtube.com/watch?v=JGNqvH9ykfA', 2019, FALSE),
       ('Descending', 'Tool', 'Fear Inoculum', 'Rock', '00:13:38',
        'https://music.apple.com/us/album/descending/1475686696?i=1475687061',
        'https://open.spotify.com/album/7acEciVtnuTzmwKptkjth5?highlight=spotify:track:0aTiUssEOy0Mt69bsavj6K',
        'https://www.youtube.com/watch?v=PcSoLwFisaw', 2019, FALSE),
       ('LOVE FOOLISH', 'TWICE', 'Feel Special', 'K-Pop', '00:03:11',
        'https://music.apple.com/us/album/love-foolish/1556087002?i=1556087221',
        'https://open.spotify.com/album/5MmndGNrJgTLd5W7HNmVST?highlight=spotify:track:5ipJi9h2ghaThn6EUwO3B2',
        'https://www.youtube.com/watch?v=PeFXRIJXYZo', 2019, FALSE),
       ('Blow Me (feat. Jason Aalon Butler)', 'The Used', 'Heartwork', 'Rock', '00:03:21',
        'https://music.apple.com/us/album/blow-me-feat-jason-aalon-butler/1496886925?i=1496887423',
        'https://open.spotify.com/album/7nuTopxM42gzBYG7iPbAGp?highlight=spotify:track:1vS7jjy99wfMVVC9nzZtX1',
        'https://www.youtube.com/watch?v=pCvbyZn24t4', 2019, TRUE),

       ('Animals', 'Architects', 'For Those That Wish to Exist', 'Hard Rock', '00:04:04',
        'https://music.apple.com/us/album/animals/1533388849?i=1533388859',
        'https://open.spotify.com/album/7qemUq4n71awwVPOaX7jw4?highlight=spotify:track:5ofoB8PFmocBXFBEWVb6Vz',
        'https://www.youtube.com/watch?v=jdWhJcrrjQs', 2020, FALSE),
       ('Lemons', 'Ashley Tisdale', 'Lemons - Single', 'Pop', '00:02:39',
        'https://music.apple.com/us/album/lemons/1514508650?i=1514508651',
        'https://open.spotify.com/album/0thw4IDGZK9W9ZCfkHhG6l?highlight=spotify:track:0Wes7TZVfPo4M1TK5c3F8Y',
        'https://www.youtube.com/watch?v=sqI3erQEmMU', 2020, TRUE),
       ('Kingslayer (feat. BABYMETAL)', 'Bring Me The Horizon', 'POST HUMAN: SURVIVAL HORROR', 'Hard Rock', '00:03:40',
        'https://music.apple.com/us/album/kingslayer-feat-babymetal/1535067172?i=1535067323',
        'https://open.spotify.com/album/0e1WaSNDZnoPixaxDNdWo4?highlight=spotify:track:7CAbF0By0Fpnbiu6Xn5ZF7',
        'https://www.youtube.com/watch?v=fKyXvNkGQKc', 2020, FALSE),
       ('Paradise', 'DREAMCATCHER', 'Dystopia: The Tree of Language', 'K-Pop', '00:04:04',
        'https://music.apple.com/us/album/paradise/1891635493?i=1891635794',
        'https://open.spotify.com/album/7no7EZnKgoRWBbGMjZo9gB?highlight=spotify:track:2zCUaUgenXGzhMQztjf9qd',
        'https://www.youtube.com/watch?v=BuaGs9W6Un8', 2020, FALSE),
       ('PRESENCE IS STRENGTH', 'FEVER 333', 'PRESENCE IS STRENGTH - Single', 'Rock', '00:02:42',
        'https://music.apple.com/us/album/presence-is-strength/1501840074?i=1501840075',
        'https://open.spotify.com/album/3fjDg2XiszYmNywWZqIQRT?highlight=spotify:track:7kpYImqzb3AswxjNr1vkeq',
        'https://www.youtube.com/watch?v=GAjEP4KUDJM', 2020, TRUE),
       ('MAGO', 'GFRIEND', '回:Walpurgis Night', 'K-Pop', '00:03:19',
        'https://music.apple.com/us/album/mago/1754053445?i=1754053450',
        'https://open.spotify.com/album/6keRNtq7CnhNrD2EIKOA6h?highlight=spotify:track:46WaBBaEHzgbN88Ew0nh50',
        'https://www.youtube.com/watch?v=LmBYPXGqtss', 2020, FALSE),
       ('Age of Machine', 'Greta Van Fleet', 'The Battle At Garden''s Gate', 'Rock', '00:06:54',
        'https://music.apple.com/us/album/age-of-machine/1543007580?i=1543008237',
        'https://open.spotify.com/album/7kjLKy9JLbwM9F7eDQEnd2?highlight=spotify:track:6XALorRRo9aQdBIQN0UWyn',
        'https://www.youtube.com/watch?v=sAGNTWmVOAo', 2020, TRUE),
       ('Rolled Down Window', 'John the Ghost', 'I Only Want to Live Once', 'Alternative', '00:04:04',
        'https://music.apple.com/us/album/rolled-down-window/1551405158?i=1551405166',
        'https://open.spotify.com/album/7AQHLGuRwBK22p67rzjpBT?highlight=spotify:track:7Cskx1g6e81UoLD3Qou3rd',
        'https://www.youtube.com/watch?v=lm1BQPq1Wvc', 2020, FALSE),
       ('A Sweeter Place (feat. Kid Cudi)', 'Selena Gomez', 'Rare', 'Pop', '00:04:23',
        'https://music.apple.com/us/album/a-sweeter-place-feat-kid-cudi/1488413282?i=1488413386',
        'https://open.spotify.com/album/3YPFaTR7WMi1Hd4NVKdCJx?highlight=spotify:track:4bb94wZVF1cX66vQjNeJTX',
        'https://www.youtube.com/watch?v=HwV4t4yuSxA', 2020, FALSE),
       ('Brothers (feat. Eddy Capparelli)', 'SIAMES', 'Home', 'Indie Pop', '00:04:06',
        'https://music.apple.com/us/album/brothers-feat-eddy-capparelli/1495889131?i=1495889434',
        'https://open.spotify.com/album/54Tu4voMoq7IC5lEAFiOsn?highlight=spotify:track:2Hla6QVdb2fJhQonnGLksC',
        'https://www.youtube.com/watch?v=xuX3WQzO9kc', 2020, FALSE),
       ('Am I Talking To The Champagne (Or Talking To You)', 'The Struts', 'Strange Days', 'Rock', '00:05:47',
        'https://music.apple.com/us/album/am-i-talking-to-the-champagne-or-talking-to-you/1530101176?i=1530101585',
        'https://open.spotify.com/album/4hHHHg7bYSXH803dEsSyl8?highlight=spotify:track:05h4hfkCzXIVBjju9chzxa',
        'https://www.youtube.com/watch?v=rRLTlryamaU', 2020, FALSE),
       ('Protect The Land', 'System of a Down', 'Protect The Land/Genocidal Humanoidz - Single', 'Rock', '00:05:08',
        'https://music.apple.com/us/album/protect-the-land/1538616280?i=1538616285',
        'https://open.spotify.com/album/00OQIrRjQgZmacSnjK8L7M?highlight=spotify:track:11ajcVj3qSyyMPUpTJUP3y',
        'https://www.youtube.com/watch?v=XqmknZNg1yw', 2020, TRUE),
       ('UP NO MORE', 'TWICE', 'Eyes wide open', 'K-Pop', '00:03:34',
        'https://music.apple.com/us/album/up-no-more/1535654236?i=1535654254',
        'https://open.spotify.com/album/33jypnU7WULxPaVrjj4RXH?highlight=spotify:track:1LiNP5q2thWScdvCRkJ584',
        'https://www.youtube.com/watch?v=Qgylz1pLFE0', 2020, FALSE),

       ('Family', 'Badflower', 'This Is How The World Ends', 'Alternative', '00:04:07',
        'https://music.apple.com/us/album/family/1573809059?i=1573809127',
        'https://open.spotify.com/album/1A2doQQJcGdh1ORygfbEp9?highlight=spotify:track:3z67pAKSP7DQkRpWOD28T1',
        'https://www.youtube.com/watch?v=Rwsh17a9Lqk', 2021, FALSE),
       ('Spirit', 'The Blue Stones', 'Hidden Gems', 'Rock', '00:04:03',
        'https://music.apple.com/us/album/spirit/1545703292?i=1545703570',
        'https://open.spotify.com/album/6uI7YirquMLS8hkRFgJ16B?highlight=spotify:track:57xWuijtGZYZTz2zJE7Ohg',
        'https://www.youtube.com/watch?v=psTtPoCdRcA', 2021, FALSE),
       ('Snowblood', 'ERRA', 'ERRA', 'Metal', '00:04:14',
        'https://music.apple.com/us/album/snowblood/1762957662?i=1762957663',
        'https://open.spotify.com/album/3OuLJUIq1lBj8EUaoIQvWZ?highlight=spotify:track:3pkfVWPONcWQU5UAxWyALx',
        'https://www.youtube.com/watch?v=ruGgo1MkUj8', 2021, TRUE),
       ('Broken Bells', 'Greta Van Fleet', 'The Battle at Garden''s Gate', 'Rock', '00:05:51',
        'https://music.apple.com/us/album/broken-bells/1543007580?i=1543008231',
        'https://open.spotify.com/album/7kjLKy9JLbwM9F7eDQEnd2?highlight=spotify:track:2lXGcshKbu1QSq04zEIjAD',
        'https://www.youtube.com/watch?v=6vjLrCqedXs', 2021, FALSE),
       ('Bad Place', 'The Hunna', 'I''d Rather Die Than Let You In (Deluxe)', 'Alternative', '00:02:20',
        'https://music.apple.com/us/album/bad-place/1575713141?i=1575713288',
        'https://open.spotify.com/album/1jtNDdYU7WEokWY2tURRfc?highlight=spotify:track:5niZzVWeTlRRYvfb9De9LC',
        'https://www.youtube.com/watch?v=Q39Uidgnip0', 2021, FALSE),
       ('Lilac', 'IU', 'LILAC', 'K-Pop', '00:03:34',
        'https://music.apple.com/us/album/lilac/1560113132?i=1560113134',
        'https://open.spotify.com/album/01dPJcwyht77brL4JQiR8R?highlight=spotify:track:5xrtzzzikpG3BLbo4q1Yul',
        'https://www.youtube.com/watch?v=v7bnOxV4jAc', 2021, FALSE),
       ('Dirty, Pretty, Beautiful', 'The Maine', 'XOXO: From Love & Anxiety In Real Time', 'Alternative', '00:03:52',
        'https://music.apple.com/us/album/dirty-pretty-beautiful/1812071558?i=1812072310',
        'https://open.spotify.com/album/0XFA5pfYjdDx6tnPLEaeDz?highlight=spotify:track:065QVuYqbXzqPCSsc21AYZ',
        'https://www.youtube.com/watch?v=t7aHAujisVY', 2021, FALSE),
       ('Let The Bad Times Roll', 'The Offspring', 'Let The Bad Times Roll', 'Rock', '00:03:19',
        'https://music.apple.com/us/album/let-the-bad-times-roll/1579605726?i=1579605740',
        'https://open.spotify.com/album/7CiSh3Wv5DrOmoxIZhzBYm?highlight=spotify:track:0O2UONKvVfdwDyefKh5Yo1',
        'https://www.youtube.com/watch?v=J6vpedfGPwY', 2021, FALSE),
       ('good 4 u', 'Olivia Rodrigo', 'SOUR', 'Alternative', '00:02:58',
        'https://music.apple.com/us/album/good-4-u/1560735414?i=1560735551',
        'https://open.spotify.com/album/6s84u2TUpR3wdUv4NgKA2j?highlight=spotify:track:4ZtFanR9U6ndgddUvNcjcG',
        'https://www.youtube.com/watch?v=gNi_6U5Pm_o', 2021, FALSE),
       ('Always The Same (feat. Barbie Williams)', 'SIAMES', 'Always The Same - Single', 'Indie Rock', '00:03:41',
        'https://music.apple.com/us/album/always-the-same/1551191206?i=1551191212',
        'https://open.spotify.com/album/5smtb02qp5n4JNEacmp0oz?highlight=spotify:track:2yTzHEHhjw4NCabkoTA8v0',
        'https://www.youtube.com/watch?v=5Pna5YmmP34', 2021, TRUE),
       ('Earth is a Black Hole', 'Teenage Wrist', 'Earth is a Black Hole', 'Alternative', '00:02:56',
        'https://music.apple.com/us/album/earth-is-a-black-hole/1533745059?i=1533745071',
        'https://open.spotify.com/album/2mrdThr7I4qOOivf2KSgwD?highlight=spotify:track:13a2v5JNOROuvh2MBMWxqb',
        'https://www.youtube.com/watch?v=Czrv46nFT7I', 2021, FALSE),
       ('F.I.L.A (Fall In Love Again)', 'TWICE', 'Formula of Love: O + T = <3', 'K-Pop', '00:03:11',
        'https://music.apple.com/us/album/f-i-l-a-fall-in-love-again/1591509653?i=1591509663',
        'https://open.spotify.com/album/5052Ip89wdW8EGdpjEpNeq?highlight=spotify:track:4O1WbQwMV0W6Y2dUCvwoBx',
        'https://www.youtube.com/watch?v=I4xliZW07tk', 2021, FALSE),
       ('Aloo Gobi', 'Weezer', 'OK Human', 'Alternative', '00:03:04',
        'https://music.apple.com/us/album/aloo-gobi/1549768766?i=1549768924',
        'https://open.spotify.com/album/0dL9rGQxUeIqpiUndXaQLl?highlight=spotify:track:6rSJz9u8Y9xixsh5fKu9hV',
        'https://www.youtube.com/watch?v=CSYdDQEfYhM', 2021, FALSE),

       ('be very afraid', 'Architects', 'the classic symptoms of a broken spirit', 'Hard Rock', '00:04:20',
        'https://music.apple.com/us/album/be-very-afraid/1630014304?i=1630014645',
        'https://open.spotify.com/album/5ncQrFYuAZYrNcbzbJjgL4?highlight=spotify:track:1nXWhLumXogqFeijfa1uJd',
        'https://www.youtube.com/watch?v=edDxry_TXhE', 2022, FALSE),
       ('Monochrome', 'BABYMETAL', 'THE OTHER ONE', 'Metal', '00:03:57',
        'https://music.apple.com/us/album/monochrome/1830276178?i=1830276359',
        'https://open.spotify.com/album/0gboAM5pPE6N4WBgCmq70t?highlight=spotify:track:73SsGfqjQv6oUxDaC9w8es',
        'https://www.youtube.com/watch?v=FpPBPQUdFx8', 2022, TRUE),
       ('Don''t Miss', 'The Blue Stones', 'Pretty Monster', 'Rock', '00:03:08',
        'https://music.apple.com/us/album/dont-miss/1643862547?i=1643862550',
        'https://open.spotify.com/album/1ZSM06t6wMNeIaNMXxCuL6?highlight=spotify:track:1ggbqc7jhg454UpFfSmdam',
        'https://www.youtube.com/watch?v=vzKL1JqMa3I', 2022, FALSE),
       ('A Disappearing Act', 'Coheed and Cambria', 'Vaxis II: A Window of the Waking Mind', 'Hard Rock', '00:03:30',
        'https://music.apple.com/us/album/a-disappearing-act/1594201540?i=1594201872',
        'https://open.spotify.com/album/5YRtvIMApwxnUTcWUBcaON?highlight=spotify:track:04flu1A6UXP4Stissk3G1l',
        'https://www.youtube.com/watch?v=qmMI6fEpxns', 2022, FALSE),
       ('Cherry (Real Miracle)', 'DREAMCATCHER', 'Apocalypse: Save us', 'K-Pop', '00:03:15',
        'https://music.apple.com/us/album/cherry-real-miracle-ji-u-solo/1893529282?i=1893529290',
        'https://open.spotify.com/album/42mMFBIWT599FmtWK5op4a?highlight=spotify:track:2TZYvSsXSvigKQShBS2OPE',
        'https://www.youtube.com/watch?v=2L0q-nWS1xA', 2022, FALSE),
       ('Neon', 'Electric Callboy', 'TEKKNO', 'Metal', '00:03:12',
        'https://music.apple.com/us/album/neon/1618490079?i=1618490422',
        'https://open.spotify.com/album/1RCinQ2MnD8yNRsXKpeKFg?highlight=spotify:track:5Ax3CrEaFiQHb65JMijp2J',
        'https://www.youtube.com/watch?v=GtYWrVoP5Ok', 2022, FALSE),
       ('Nigh to Silence', 'ERRA', 'ERRA', 'Rock', '00:05:05',
        'https://music.apple.com/us/album/nigh-to-silence/1762964038?i=1762964053',
        'https://open.spotify.com/album/6FzCpxT035ityoufuiWlGU?highlight=spotify:track:08BV91W7OizUACboEkkx4p',
        'https://www.youtube.com/watch?v=mDKIIDQczWI', 2022, FALSE),
       ('Sour', 'He Is Legend', 'Endless Hallway', 'Rock', '00:03:47',
        'https://music.apple.com/us/album/sour/1676711261?i=1676711743',
        'https://open.spotify.com/album/3kKcRKhi6y0RrOdVeljWpI?highlight=spotify:track:03PwIVcBHZ2xeJ0sR7o9g4',
        'https://www.youtube.com/watch?v=8S3a84p8c30', 2022, FALSE),
       ('Circles', 'The Hunna', 'The Hunna', 'Rock', '00:03:24',
        'https://music.apple.com/us/album/circles/1634534556?i=1634535074',
        'https://open.spotify.com/album/6o0Cd4hfhFGnVeYSugnzII?highlight=spotify:track:2Y9qfaLaSgFKoXrsZt9KI6',
        'https://www.youtube.com/watch?v=ePzZh-2tikU', 2022, FALSE),
       ('Loved You a Little (feat. Taking Back Sunday & Charlotte Sands)', 'The Maine', 'Loved You A Little - Single',
        'Alternative', '00:03:27',
        'https://music.apple.com/us/album/loved-you-a-little/1812628195?i=1812628196',
        'https://open.spotify.com/album/2tgx0FJj6dtx3GzTm1Jbbd?highlight=spotify:track:0IPKskRI33eRXjUhNUr9b5',
        'https://www.youtube.com/watch?v=MAiG9eMRc64', 2022, TRUE),
       ('My Way (feat. Barbie Williams)', 'SIAMES', 'My Way (Single Version) - Single', 'Pop', '00:02:59',
        'https://music.apple.com/us/album/my-way-single-version/1644761389?i=1644761401',
        'https://open.spotify.com/album/4bTBjP3iiEypRH21Q5RzEu?highlight=spotify:track:2aG8speTt7aje2gii3g6UK',
        'https://www.youtube.com/watch?v=Z9ZlS7i2Xvc', 2022, TRUE),
       ('Talk that Talk', 'TWICE', 'BETWEEN 1&2', 'K-Pop', '00:02:57',
        'https://music.apple.com/us/album/talk-that-talk/1635656322?i=1635656417',
        'https://open.spotify.com/album/3NZ94nQbqimcu2i71qhc4f?highlight=spotify:track:0RDqNCRBGrSegk16Avfzuq',
        'https://www.youtube.com/watch?v=k6jqx9kZgPM', 2022, FALSE),
       ('What Happens After You?', 'Weezer', 'SZNZ: Autumn', 'Alternative', '00:03:20',
        'https://music.apple.com/us/album/what-happens-after-you/1645304165?i=1645304169',
        'https://open.spotify.com/album/1ZuTYUdoALghOAKTISys6n?highlight=spotify:track:5x7Ffxc1Obg13x5IzM1XXV',
        'https://www.youtube.com/watch?v=uWWuw4Y-s0w', 2022, FALSE),

       ('Cosmic', 'Avenged Sevenfold', 'Life Is But a Dream...', 'Hard Rock', '00:07:31',
        'https://music.apple.com/us/album/cosmic/1676708908?i=1676708916',
        'https://open.spotify.com/album/50YNY0xy9uJ0U9eFQBdLJa?highlight=spotify:track:1xA87lWGnZlIjG8tw4327F',
        'https://www.youtube.com/watch?v=NxFE5YOErcg', 2023, FALSE),
       ('Time Wave', 'BABYMETAL', 'THE OTHER ONE', 'Metal', '00:04:50',
        'https://music.apple.com/us/album/time-wave/1830276178?i=1830276355',
        'https://open.spotify.com/album/0gboAM5pPE6N4WBgCmq70t?highlight=spotify:track:4I5JsMUy4rCzkrymv15DbP',
        'https://www.youtube.com/watch?v=vKcwoljt4WA', 2023, FALSE),
       ('Feast Is Over', 'Calva Louise', 'Over the Threshold', 'Alternative', '00:03:12',
        'https://music.apple.com/us/album/feast-is-over/1702038051?i=1702038062',
        'https://open.spotify.com/album/6j7try3OyUBLLNd0PfvWXU?highlight=spotify:track:63PhRyJ0fX8XBJPN2Hg2w3',
        'https://www.youtube.com/watch?v=k84XVjdZKz0', 2023, FALSE),
       ('Cupid', 'FIFTY FIFTY', 'The Beginning', 'K-Pop', '00:02:55',
        'https://music.apple.com/us/album/cupid/1762390380?i=1762390691',
        'https://open.spotify.com/album/5W30YJavMoHwG64cPD4L9C?highlight=spotify:track:4TqmTBSWsZXMj3LouLEvXn',
        'https://www.youtube.com/watch?v=Qc7_zRjH808', 2023, FALSE),
       ('Dramatic', 'Idina Menzel', 'Drama Queen', 'Pop', '00:03:13',
        'https://music.apple.com/us/album/dramatic/1692527112?i=1692527115',
        'https://open.spotify.com/album/0kMmfTz3OwAh73dSCN3FpW?highlight=spotify:track:1HmgWp6HhxeQTUp308gGch',
        'https://www.youtube.com/watch?v=-vuwW40M5n4', 2023, FALSE),
       ('I AM', 'IVE', 'I''ve IVE', 'K-Pop', '00:03:04',
        'https://music.apple.com/us/album/i-am/1680047093?i=1680047366',
        'https://open.spotify.com/album/38VzP4yWfHdHafITKKRHEB?highlight=spotify:track:70t7Q6AYG6ZgTYmJWcnkUM',
        'https://www.youtube.com/watch?v=6ZUIwj3FgUY', 2023, FALSE),
       ('LOVE AGAIN', 'The Kid LAROI', 'THE FIRST TIME (DELUXE VERSION)', 'Pop', '00:02:27',
        'https://music.apple.com/us/album/love-again/1895174074?i=6763128344',
        'https://open.spotify.com/album/5FYre0OdHLE1MnJ1bHTx1f?highlight=spotify:track:3HYuHTo8slisIQdY2XZWT8',
        'https://www.youtube.com/watch?v=Mc-wFcieEmU', 2023, FALSE),
       ('how to exit a room', 'The Maine', 'The Maine', 'Alternative', '00:03:45',
        'https://music.apple.com/us/album/how-to-exit-a-room/1812073322?i=1812073326',
        'https://open.spotify.com/album/07GEuImz0GyNXH61jKqZi2?highlight=spotify:track:7e61iFzE2MvK1gJ276XXmX',
        'https://www.youtube.com/watch?v=SArdZ4CW2OI', 2023, FALSE),
       ('Ghost Of Me', 'Make Them Suffer', 'Make Them Suffer', 'Metal', '00:03:51',
        'https://music.apple.com/us/album/ghost-of-me/1757700305?i=1757701230',
        'https://open.spotify.com/album/2Rjxd0Hq8yoQ3W9mDLBgLE?highlight=spotify:track:4iJXyzJZEUpez7GWQ8ekBr',
        'https://www.youtube.com/watch?v=bAp3BPUfj2o', 2023, TRUE),
       ('Do not touch', 'MISAMO', 'Masterpiece', 'J-Pop', '00:03:06',
        'https://music.apple.com/us/album/do-not-touch/1691852603?i=1691852612',
        'https://open.spotify.com/album/3qmO83vO1SsdmP1Y0ljhSQ?highlight=spotify:track:5gq7xM6eI16osBO2U581NL',
        'https://www.youtube.com/watch?v=woKq2sD8xho', 2023, FALSE),
       ('OMG', 'NewJeans', 'OMG - Single', 'K-Pop', '00:03:32',
        'https://music.apple.com/us/album/omg/1659513441?i=1659513445',
        'https://open.spotify.com/album/45ozep8uHHnj5CCittuyXj?highlight=spotify:track:65FftemJ1DbbZ45DUfHJXE',
        'https://www.youtube.com/watch?v=_ZAgIHmHLdc', 2023, TRUE),
       ('Essence (feat. Super Computer)', 'Oliver Tree', 'Alone In A Crowd', 'Alternative', '00:02:48',
        'https://music.apple.com/us/album/essence-feat-super-computer/1693015199?i=1693015501',
        'https://open.spotify.com/album/0x6KKhlAIZsuU6SVgSX9E9?highlight=spotify:track:3YQHgTo0898GHXRC2byH52',
        'https://www.youtube.com/watch?v=9mAeFNERZoI', 2023, FALSE),
       ('SET ME FREE (ENG)', 'TWICE', 'READY TO BE', 'K-Pop', '00:03:02',
        'https://music.apple.com/us/album/set-me-free-eng/1669081578?i=1669081814',
        'https://open.spotify.com/album/7hzP5i7StxYG4StECA0rrJ?highlight=spotify:track:6bkTxw6m6vl8Oc3xtKBXN0',
        'https://www.youtube.com/watch?v=Cczo7nazBGA', 2023, FALSE),

       ('upside down', 'AVRALIZE', 'liminal', 'Metal', '00:04:05',
        'https://music.apple.com/us/album/upside-down/1827560906?i=1827561164',
        'https://open.spotify.com/album/0KgQQBn420fOjGTUuOkO7p?highlight=spotify:track:5a4Zs7sYpVEvXikDOCWdyD',
        'https://www.youtube.com/watch?v=vjJMUD4CbY8', 2024, TRUE),
       ('RATATA (feat. Electric Callboy)', 'BABYMETAL', 'METAL FORTH', 'Metal', '00:03:36',
        'https://music.apple.com/us/album/ratatata/1807174668?i=1807175031',
        'https://open.spotify.com/album/7JAioi7aQOS0VenAg3xfrp?highlight=spotify:track:2S3u18aJF8eExll5dYwSJb',
        'https://www.youtube.com/watch?v=EDnIEWyVIlE', 2024, FALSE),
       ('Houdini', 'Eminem', 'The Death of Slim Shady (Coup De Grâce)', 'Rap', '00:03:47',
        'https://music.apple.com/us/album/houdini/1755022177?i=1755022500',
        'https://open.spotify.com/album/5kuRwJLsld1jXzxxVERPMC?highlight=spotify:track:2SkkJtLz1Ro29DXWvj9mIJ',
        'https://www.youtube.com/watch?v=22tVWwmTie8', 2024, FALSE),
       ('I stan U', 'IU', 'The Winning - EP', 'K-Pop', '00:03:13',
        'https://music.apple.com/us/album/i-stan-u/1731352613?i=1731352618',
        'https://open.spotify.com/album/08CvAj58nVMpq1Nw7T6maj?highlight=spotify:track:0NnXG9qhpf0E6elVQdWLE7',
        'https://www.youtube.com/watch?v=_ZfT3M6ZKEM', 2024, FALSE),
       ('Suffocate (feat. Poppy)', 'Knocked Loose', 'You Won''t Go Before You''re Supposed To', 'Metal', '00:02:45',
        'https://music.apple.com/us/album/suffocate-feat-poppy/1732119298?i=1732119474',
        'https://open.spotify.com/album/2sLBMdUF5HYNB0voqWs4K3?highlight=spotify:track:6PXYOVPBzO3xojFhQAvmde',
        'https://www.youtube.com/watch?v=RAuuVY__KQ0', 2024, FALSE),
       ('Harrison Ave', 'Lil Dicky', 'Penith', 'Rap', '00:06:01',
        'https://music.apple.com/us/album/harrison-ave/1720271825?i=1720272548',
        'https://open.spotify.com/album/0tD7YCpFten00qPVcMseoe?highlight=spotify:track:0q9loMHMdjPrOhHClKtZF3',
        'https://www.youtube.com/watch?v=WnAjyyXAzWU', 2024, FALSE),
       ('Lobster Popstar', 'Little Big', 'Lobster Popstar', 'Pop', '00:02:34',
        'https://music.apple.com/us/album/lobster-popstar/1732061653?i=1732061656',
        'https://open.spotify.com/album/4dEQKog3F57t9UmuvuRf88?highlight=spotify:track:1Hxgf7uMR1qdx9cSnRmXt0',
        'https://www.youtube.com/watch?v=ddloY2o51-0', 2024, FALSE),
       ('obsessed', 'Olivia Rodrigo', 'GUTS (spilled)', 'Pop', '00:02:51',
        'https://music.apple.com/us/album/obsessed/1736994915?i=1736996063',
        'https://open.spotify.com/album/1D06fz3cuob62ysTS8k6gu?highlight=spotify:track:6tNgRQ0K2NYZ0Rb9l9DzL8',
        'https://www.youtube.com/watch?v=QXcjPySjdJU', 2024, FALSE),
       ('Medicate Me (feat. Dayseeker)', 'Rain City Drive', 'Things Are Different Now', 'Rock', '00:02:47',
        'https://music.apple.com/us/album/medicate-me/1758851409?i=1758851779',
        'https://open.spotify.com/album/4NcoXQa5SMjILciWjMpHZg?highlight=spotify:track:2sfH7KtjAnWv1algu94TR5',
        'https://www.youtube.com/watch?v=v9XXDE4JhUg', 2024, FALSE),
       ('Good Graces', 'Sabrina Carpenter', 'Short n'' Sweet', 'Pop', '00:03:05',
        'https://music.apple.com/us/album/good-graces/1750307020?i=1750307081',
        'https://open.spotify.com/album/3iPSVi54hsacKKl1xIR2eH?highlight=spotify:track:102YUQbYmwdBXS7jwamI90',
        'https://www.youtube.com/watch?v=alYCYZvB3yo', 2024, FALSE),
       ('Predator', 'Siamese', 'Elements', 'Metal', '00:03:41',
        'https://music.apple.com/us/album/predator/1742548271?i=1742548554',
        'https://open.spotify.com/album/3huRuct9l5HQFqBBe1A1OU?highlight=spotify:track:6KzvDJvnykZfh2G3uslGnx',
        'https://www.youtube.com/watch?v=rVpDs67Y7i8', 2024, FALSE),
       ('Soft Spine', 'Spiritbox', 'Tsunami Sea', 'Metal', '00:03:04',
        'https://music.apple.com/us/album/soft-spine/1779147456?i=1779147890',
        'https://open.spotify.com/album/79sg58t1vRpcxudpP9uPtg?highlight=spotify:track:4bkPAARkDov1lV05emEF7a',
        'https://www.youtube.com/watch?v=80VTmBAnTSE', 2024, FALSE),
       ('I GOT YOU', 'TWICE', 'With YOU-th - EP', 'K-Pop', '00:02:53',
        'https://music.apple.com/us/album/i-got-you/1726087580?i=1726087587',
        'https://open.spotify.com/album/575TQDOQqc0MAheeEeKWUR?highlight=spotify:track:0mgveJEIGjcN51w4JIQtI6',
        'https://www.youtube.com/watch?v=haf67eKF0uo', 2024, FALSE),

       ('Obsidian', 'ACCVSED', 'Dealers of Doom', 'Metal', '00:02:45',
        'https://music.apple.com/us/album/obsidian/1808886714?i=1808887119',
        'https://open.spotify.com/album/03KPEoSUumnwMBDGTSGQeP?highlight=spotify:track:45OHlPTnq3jvtR0zPy2RaM',
        'https://www.youtube.com/watch?v=Mk28mcdoaYM', 2025, FALSE),
       ('Everything Ends', 'Architects', 'The Sky, the Earth & All Between', 'Hard Rock', '00:03:40',
        'https://music.apple.com/us/album/everything-ends/1774393621?i=1774393631',
        'https://open.spotify.com/album/2W82VyyIFAXigJEiLm5TT1?highlight=spotify:track:3yC1soClolbb2jFH7XIPqd',
        'https://www.youtube.com/watch?v=gEl5Q3SXJwc', 2025, FALSE),
       ('twilight zone', 'Ariana Grande', 'eternal sunshine deluxe: brighter days ahead', 'Pop', '00:03:18',
        'https://music.apple.com/us/album/twilight-zone/1800578808?i=1800579242',
        'https://open.spotify.com/album/6kXXIMyzRgQeai4A0DsXOn?highlight=spotify:track:1UrwJzlNC2oaTlxj1OZmcu',
        'https://www.youtube.com/watch?v=x1XIJM6spaE', 2025, FALSE),
       ('medicine', 'AVRALIZE', 'liminal', 'Metal', '00:03:50',
        'https://music.apple.com/us/album/medicine/1827560906?i=1827560907',
        'https://open.spotify.com/album/0KgQQBn420fOjGTUuOkO7p?highlight=spotify:track:5eZ5AWGvhd6lGnUk4IEQQe',
        'https://www.youtube.com/watch?v=eVXNkPbHSso', 2025, FALSE),
       ('Sunset Kiss (feat. Polyphia)', 'BABYMETAL', 'METAL FORTH', 'Metal', '00:03:33',
        'https://music.apple.com/us/album/sunset-kiss/1807174668?i=1807175039',
        'https://open.spotify.com/album/7JAioi7aQOS0VenAg3xfrp?highlight=spotify:track:5MYlEdN2pfbl0S1qCToSvQ',
        'https://www.youtube.com/watch?v=9KO4jIo4x_E', 2025, FALSE),
       ('Cyclone', 'Future Palace', 'Resurgence', 'Metal', '00:04:02',
        'https://music.apple.com/us/album/cyclone/6768276978?i=6768277000',
        'https://open.spotify.com/album/1RUL7zZjtQO9z1xbrNkhUw?highlight=spotify:track:37CZKQjOFXTMKzvXzmYIa1',
        'https://www.youtube.com/watch?v=6boTK53X7bk', 2025, TRUE),
       ('Golden', 'HUNTR/X', 'KPop Demon Hunters', 'K-Pop', '00:03:14',
        'https://music.apple.com/us/album/golden/1820264137?i=1820264150',
        'https://open.spotify.com/album/14JkAa6IiFaOh5s0nMyMU9?highlight=spotify:track:1CPZ5BxNNd0n0nF4Orb9JS',
        'https://www.youtube.com/watch?v=hohuFW0zQUw', 2025, FALSE),
       ('HOT', 'LE SSERAFIM', 'HOT - EP', 'K-Pop', '00:02:24',
        'https://music.apple.com/us/album/hot/1799278610?i=1799278617',
        'https://open.spotify.com/album/3lyRrGhXCCMbt4jVO9Wur2?highlight=spotify:track:406IpEtZPvbxApWTGM3twY',
        'https://www.youtube.com/watch?v=r9AEGPB6qIU', 2025, FALSE),
       ('Caramel', 'Sleep Token', 'Even in Arcadia', 'Metal', '00:04:50',
        'https://music.apple.com/us/album/caramel/1800532611?i=1800533447',
        'https://open.spotify.com/album/1lS7FeRcSUuIGqyg99UGpj?highlight=spotify:track:1QrbZhFYlViXd60g130vw1',
        'https://www.youtube.com/watch?v=4iSvoQNfrrk', 2025, FALSE),
       ('Revolver', 'Thornhill', 'BODIES', 'Hard Rock', '00:04:15',
        'https://music.apple.com/us/album/revolver/1787004036?i=1787004038',
        'https://open.spotify.com/album/5bJeb7bvHrxNvZ6UskCoqm?highlight=spotify:track:1OmtYfgEqFoU8EhG3IQzrF',
        'https://www.youtube.com/watch?v=azIlWN7VGi4', 2025, FALSE),
       ('Kill Me Fast', 'Three Days Grace', 'Alienation', 'Rock', '00:03:17',
        'https://music.apple.com/us/album/kill-me-fast/1811868492?i=1811868496',
        'https://open.spotify.com/album/3qNCqYQyWvvgTapGWLTQsk?highlight=spotify:track:2CNqbrPKODRQxE8gCkHqEN',
        'https://www.youtube.com/watch?v=XM72AOmQcrc', 2025, FALSE),
       ('MARS', 'TWICE', 'THIS IS FOR', 'K-Pop', '00:02:21',
        'https://music.apple.com/us/album/mars/1813490993?i=1813491006',
        'https://open.spotify.com/album/02dUOPB3MtmV5fawzaZiq6?highlight=spotify:track:6B2WCk6chRbS7QHIeUYD1H',
        'https://www.youtube.com/watch?v=N1ExjhcpLso', 2025, FALSE),
       ('Good Luck', 'UAU', 'Playlist #You Are You - EP', 'K-Pop', '00:02:50',
        'https://music.apple.com/us/album/good-luck/1815640586?i=1815640590',
        'https://open.spotify.com/album/0Z9CrKIgLP09vWer1NGZBJ?highlight=spotify:track:0udrtzeQZZ0JiAxISndWnk',
        'https://www.youtube.com/watch?v=KH-3HLUBCQo', 2025, FALSE)

ON CONFLICT (song_name, artist) DO NOTHING;

COMMIT;
